package DSMSApp;

import java.util.Calendar;
import java.util.TimeZone;

/**
* DSMSApp/Date.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSMS.idl
* Thursday, October 15, 2020 12:45:40 o'clock AM EDT
*/

public final class Date implements org.omg.CORBA.portable.IDLEntity
{
  public short Day = (short)0;
  public short Month = (short)0;
  public short Year = (short)0;

  public Date ()
  {
  } // ctor

  public Date (short _Day, short _Month, short _Year)
  {
    Day = _Day;
    Month = _Month;
    Year = _Year;
  } // ctor
  
  public String toString() {
	  return Day + "-" + Month + "-" + Year;
  }
  
  public String toString2() {
	  return "" + Day + Month + Year;
  }
  
  public static DSMSApp.Date convertToDate(String dop){
		short day, month, year;

		if(dop.matches("[0-9][0-9][0-9]{4}")) {
			day = Short.parseShort(dop.substring(0,1));
			month = Short.parseShort(dop.substring(1,2));
			year = Short.parseShort(dop.substring(2));
		}else if(dop.matches("[0-9]{2}[0-9][0-9]{4}")) {
			day = Short.parseShort(dop.substring(0,2));
			month = Short.parseShort(dop.substring(2,3));
			year = Short.parseShort(dop.substring(3));
		}else if(dop.matches("[0-9][0-9]{2}[0-9]{4}")) {
			day = Short.parseShort(dop.substring(0,1));
			month = Short.parseShort(dop.substring(1,3));
			year = Short.parseShort(dop.substring(3));
		}else{
			day = Short.parseShort(dop.substring(0,2));
			month = Short.parseShort(dop.substring(2,4));
			year = Short.parseShort(dop.substring(4));
		}
		
		DSMSApp.Date dateOfPurchase = new DSMSApp.Date(day, month, year);
		return dateOfPurchase;
	}
  
  public static Date getCurrentDate() {
		Calendar calendar = Calendar.getInstance(TimeZone.getDefault());
		java.util.Date date = calendar.getTime();
		short day = (short)calendar.get(Calendar.DATE);
		short month = (short)(calendar.get(Calendar.MONTH) + 1);
		short year = (short)calendar.get(Calendar.YEAR);
		return new Date(day, month, year);
  }

} // class Date
