package DSMSApp;

/**
* DSMSApp/DateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSMS.idl
* Thursday, October 15, 2020 12:45:40 o'clock AM EDT
*/

public final class DateHolder implements org.omg.CORBA.portable.Streamable
{
  public DSMSApp.Date value = null;

  public DateHolder ()
  {
  }

  public DateHolder (DSMSApp.Date initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DSMSApp.DateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DSMSApp.DateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DSMSApp.DateHelper.type ();
  }

}
