package DSMSApp;

import java.util.Calendar;
import java.util.TimeZone;

/**
* DSMSApp/Date.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSMS.idl
* Thursday, October 15, 2020 12:45:40 o'clock AM EDT
*/

public final class Date implements org.omg.CORBA.portable.IDLEntity
{
  public short Day = (short)0;
  public short Month = (short)0;
  public short Year = (short)0;

  public Date ()
  {
  } // ctor

  public Date (short _Day, short _Month, short _Year)
  {
    Day = _Day;
    Month = _Month;
    Year = _Year;
  } // ctor
  
  public String toString() {
	  return Day + "-" + Month + "-" + Year;
  }
  
  public static Date getCurrentDate() {
		Calendar calendar = Calendar.getInstance(TimeZone.getDefault());
		java.util.Date date = calendar.getTime();
		short day = (short)calendar.get(Calendar.DATE);
		short month = (short)(calendar.get(Calendar.MONTH) + 1);
		short year = (short)calendar.get(Calendar.YEAR);
		return new Date(day, month, year);
  }

} // class Date
