package DSMSApp;


/**
* DSMSApp/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DSMS.idl
* Thursday, October 15, 2020 12:45:40 o'clock AM EDT
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS
